name: Check Remote Keystore

on:
  pull_request:
    branches: [master, teekeystore]

  push:
    branches: [master, teekeystore]

  workflow_dispatch:

jobs:
  remote-keystore-check:
    runs-on: tee-ci

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "Zondax/substrate-remote-signer-example"
          ref: "tcp"
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: "remote-keystore"
          submodules: true

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Build substrate
        run: |
          cargo build --release

      - name: Build keystore
        run: |
          cd remote-keystore
          cargo build --bin server --features server

      - name: Run keystore (background)
        run: |
          cd remote-keystore
          ./target/debug/server &

      - name: Run a node (background)
        run: |
          ./target/release/substrate --chain zondaxSpecRaw.json --tmp \
          --port 30333 --ws-port 9945 --validator --execution native \
          --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
          --keystore-uri "localhost:10710" &> bootnode.out &

      - name: Check output
        run: |
          sleep 30
          cat bootnode.out
          grep -E -m 1 "finalized #[1-9][0-9]?" bootnode.out
