name: Check Remote Keystore

on:
  pull_request:
    branches: [master, teekeystore]

  push:
    branches: [master, teekeystore]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "Zondax/substrate-remote-signer-example"
          ref: "tcp"
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: 'remote-keystore'

      - run: mv ${{ GITHUB_WORKSPACE }}/remote-keystore remote-keystore

      - name: Build substrate
        run: |
          make substrate

      - name: Run a node and check for block finalization
        run: |
          bash .github/workflows/remote-keystore/job.sh
